// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkn2NG7Da1UG-_V5TLBIaPJ-sTrOog5CY',
    appId: '1:9001095961:web:91c6968e84389ca185eb88',
    messagingSenderId: '9001095961',
    projectId: 'my-tech-library',
    authDomain: 'my-tech-library.firebaseapp.com',
    storageBucket: 'my-tech-library.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTh62dz622YF6PYXInLW2gmQWm2fHkw0o',
    appId: '1:9001095961:android:34dff4c177e363fb85eb88',
    messagingSenderId: '9001095961',
    projectId: 'my-tech-library',
    storageBucket: 'my-tech-library.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCMV8YWYvhMt7ei6PGaiV4leShrn_6H5Q',
    appId: '1:9001095961:ios:5aba67993ffacc6585eb88',
    messagingSenderId: '9001095961',
    projectId: 'my-tech-library',
    storageBucket: 'my-tech-library.appspot.com',
    iosClientId: '9001095961-pvcdfmsl3t0uvlh904ttdg6ood4melk7.apps.googleusercontent.com',
    iosBundleId: 'com.example.myBookLibrary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCMV8YWYvhMt7ei6PGaiV4leShrn_6H5Q',
    appId: '1:9001095961:ios:5aba67993ffacc6585eb88',
    messagingSenderId: '9001095961',
    projectId: 'my-tech-library',
    storageBucket: 'my-tech-library.appspot.com',
    iosClientId: '9001095961-pvcdfmsl3t0uvlh904ttdg6ood4melk7.apps.googleusercontent.com',
    iosBundleId: 'com.example.myBookLibrary',
  );
}
